name: ci

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v4
     
      -
        name: Setup .Net core 6
          uses: actions/setup-dotnet@v3
          with:
              dotnet-version: '6.0.x'
      -
        name: Restore dependencies

           run :dotnet restore
      -
        name: build app

           run :dotnet build -c release --no-restore